apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kibana.service.name }}
  namespace: {{ .Values.kibana.namespace }}
  labels:
    {{- toYaml .Values.kibana.service.labels | nindent 4 }}
spec:
  type: {{ .Values.kibana.service.type }}
  ports:
    - name: http
      port: {{ .Values.kibana.service.port }}
      targetPort: {{ .Values.kibana.service.targetPort }}
  selector:
    app: {{ .Values.kibana.service.labels.app }}
