apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.labels.app }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels.app }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      tolerations:
      {{- toYaml .Values.tolerations | nindent 6 }}
      containers:
        - name: fluentd
          image: fluent/fluentd-kubernetes-daemonset:v1.16-debian-elasticsearch7-2
          env:
            - name: FLUENT_ELASTICSEARCH_HOST
              value: {{ .Values.elasticsearch.host }}
            - name: FLUENT_ELASTICSEARCH_PORT
              value: "{{ .Values.elasticsearch.port }}"
            - name: FLUENT_ELASTICSEARCH_SCHEME
              value: "{{ .Values.elasticsearch.scheme }}"
            - name: FLUENT_ELASTICSEARCH_USER
              value: {{ .Values.elasticsearch.user }}
            - name: FLUENT_ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elastic-credentials
                  key: ELASTIC_PASSWORD
          resources:
            limits:
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          volumeMounts:
            - name: fluentd-config
              mountPath: /fluentd/etc
            - name: varlog
              mountPath: /var/log
            - name: varlogcontainers
              mountPath: /var/log/containers
              readOnly: true
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlogcontainers
          hostPath:
            path: /var/log/containers
        - name: fluentd-config
          configMap:
            name: fluentd-config