apiVersion: v1
kind: Secret
metadata:
  name: elastic-credentials
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.labels.app }}
type: Opaque
data:
  ELASTIC_PASSWORD: {{ .Values.elasticsearch.password }}