# # Default values for nebulous-workflow-executor.
# # This is a YAML-formatted file.
# # Declare variables to be passed into your templates.

image:
  repository: quay.io/nebulous/workflow-executor
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

# imagePullSecrets: []
# nameOverride: ""
# fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: workflow-executor

# podAnnotations: {}
# podLabels: {}

# podSecurityContext: {}
#   # fsGroup: 2000

# securityContext: {}
#   # capabilities:
#   #   drop:
#   #   - ALL
#   # readOnlyRootFilesystem: true
#   # runAsNonRoot: true
#   # runAsUser: 1000

service:
  type: ClusterIP
  port: 8080

metrics:
  port: 9999
  targetPort: 9999
  enabled: true

# ingress:
#   enabled: false
#   className: ""
#   annotations: {}
#     # kubernetes.io/ingress.class: nginx
#     # kubernetes.io/tls-acme: "true"
#   hosts:
#     - host: chart-example.local
#       paths:
#         - path: /
#           pathType: ImplementationSpecific
#   tls: []
#   #  - secretName: chart-example-tls
#   #    hosts:
#   #      - chart-example.local

# resources: {}
#   # We usually recommend not to specify default resources and to leave this as a conscious
#   # choice for the user. This also increases chances charts run on environments with little
#   # resources, such as Minikube. If you do want to specify resources, uncomment the following
#   # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
#   # limits:
#   #   cpu: 100m
#   #   memory: 128Mi
#   # requests:
#   #   cpu: 100m
#   #   memory: 128Mi

# livenessProbe:
#   httpGet:
#     path: /
#     port: http
# readinessProbe:
#   httpGet:
#     path: /
#     port: http

# nodeSelector: {}

# tolerations: []

# affinity: {}

argo-workflows:
  crds:
    install: true
    keep: false
  singleNamespace: true
  workflow:
    serviceAccount:
      create: true
      name: argo
    rbac:
      create: true
      serviceAccounts:
        - name: default
          namespace: argo
        - name: argo
          namespace: argo
  controller:
    workflowNamespaces: 
      - argo
    metricsConfig:
      enabled: true
    telemetryConfig:
      enabled: true
    serviceMonitor:
      enabled: true
    tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/unschedulable
        operator: Exists
      - effect: NoSchedule
        operator: Exists
    priorityClassName: system-node-critical
    nodeSelector:
      node-role.kubernetes.io/control-plane: ""
  server:
    authModes: ["server"]
    tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/unschedulable
        operator: Exists
      - effect: NoSchedule
        operator: Exists
    priorityClassName: system-node-critical
    nodeSelector:
      node-role.kubernetes.io/control-plane: ""