# Defines a Secret resource that is used for storing the Kubernetes cluster config
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: cluster-config
# Specifies the type of the Secret. Here, it's set to Opaque, indicating a generic, arbitrary data secret.
type: Opaque
# Contains the actual data to be stored in the Secret
# (.Files.Glob "files/kube.config"): This function searches for the file named "kube.config". It returns its contents
# .AsSecrets: This function converts the file content into a format suitable for being stored in a Secret. It encodes the data and formats it according to Kubernetes Secret requirements
# indent 2: This operation indents the converted data by two spaces. It's done for formatting purposes in the final YAML
data:
  {{ (.Files.Glob "files/kube.config").AsSecrets | indent 2 }}