#
# Copyright (C) 2017-2025 Institute of Communication and Computer Systems (imu.iccs.gr)
#
# This Source Code Form is subject to the terms of the Mozilla Public License, v2.0, unless
# Esper library is used, in which case it is subject to the terms of General Public License v2.0.
# If a copy of the MPL was not distributed with this file, you can obtain one at
# https://www.mozilla.org/en-US/MPL/2.0/
#

# Default values for nebulous-monitoring.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: "quay.io/nebulous/monitoring"
#  pullPolicy: IfNotPresent
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8111

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

ports:
  - name: http
    containerPort: 8111
    protocol: TCP
    public: true
    nodePort: 30111
  - name: openwire
    containerPort: 61616
    protocol: TCP
    public: false
  - name: openwire-tls
    containerPort: 61617
    protocol: TCP
    public: true
    nodePort: 31617
  - name: stomp
    containerPort: 61610
    protocol: TCP
    public: false
  - name: baguette
    containerPort: 2222
    protocol: TCP
    public: true
    nodePort: 32222

env:
  #
  # =====  EMS server configuration  =====
  #
  # ===== INITIALIZATION settings =====
  BUILD_MESSAGE: "2024-05-09 11:57:00+03:00 opendev"
  JASYPT_PASSWORD: "password"                           # +++++++++++++++++++++++++ ?????????????????
  NET_UTIL_ADDRESS_DISCOVERY_SERVICES: "-"
  EMS_IP_SETTING: "DEFAULT_IP"

  EMS_LOG_REQUESTS: "false"
  EMS_PRELOAD_APP_MODEL: "empty.yml"
  EMS_PRELOAD_CP_MODEL: ""

  CONTROL_SKIP_MVV_RETRIEVE: "true"
  CONTROL_SKIP_METASOLVER: "true"
  CONTROL_SKIP_NOTIFICATION: "true"
  CONTROL_EXIT_ALLOWED: "true"
  RESTART_EXIT_CODE: "99"

  # =====  Security and Authentication settings  =====
  CONTROL_SSL_KEY_ENTRY_GENERATE: "ALWAYS"
  CONTROL_SSL_KEYSTORE_PASSWORD: "melodic"          # +++++++++++++++++++++++++ ${P_KEYSTORE_PASSWORD}
  CONTROL_SSL_TRUSTSTORE_PASSWORD: "melodic"          # +++++++++++++++++++++++++ ${P_KEYSTORE_PASSWORD}

  JWT_SECRET: "ENC(I0mRWgH2FVDDNs4OBcdh7Z+o3lOQDa3ztaEtmnXT2HN0aClkChp/lqm9zM5HyTk0stJ7v2Di75U=)"  # +++++++++++++++++++++++++ ${P_JWT_SECRET}
  WEB_SECURITY_API_KEY_AUTHENTICATION_VALUE: "1234567890"                                               # +++++++++++++++++++++++++ ${P_WEB_API_KEY_VALUE}
  WEB_SECURITY_FORM_AUTHENTICATION_PASSWORD: "ems"                                                      # +++++++++++++++++++++++++ ${P_WEB_ADMIN_PASSWORD}

  # =====  Topic Beacon settings  =====
  BEACON_INITIAL_DELAY: "10000"
  BEACON_DELAY: "10000"

  # ===== EMS server monitoring settings =====
  EMS_SYSMON_ENABLED: "true"
  EMS_SYSMON_PERIOD: "1000"
  EMS_SYSMON_COMMAND: "./bin/sysmon.sh"

  INFO_FILES_ROOTS: "/logs, /config, /opt/ems-server/public_resources/resources"
  INFO_FILES_EXTENSIONS_BLOCKED: ".pem, .p12, .sh"

  # =====  EMS Boot (server) settings  =====
  BOOT_ENABLED: "true"

  # =====  EMS Boot Initializer (client) settings  =====
  BOOT_INITIALIZER_ENABLED: "false"

  # =====  EMS-Nebulous K8S service settings  =====
  K8S_DEPLOY_EMS_CLIENTS_ON_KUBERNETES_ENABLED: "false"
  K8S_ENABLED: "false"
  K8S_WATCHER_ENABLED: "false"

  # =====  External Broker settings  =====
  EXTERNAL_ENABLED: "true"
  EXTERNAL_BROKER_ADDRESS: "nebulous-activemq"
  EXTERNAL_BROKER_PORT: "5672"
  EXTERNAL_BROKER_USERNAME: "nebulous"
  EXTERNAL_BROKER_PASSWORD: "admin"

  EXTERNAL_CONNECTION_INFO_COLLECTION_MODE: "CONFIG"
  EXTERNAL_BROKER_SERVICE_NAME: "nebulous-activemq"
  EXTERNAL_BROKER_SERVICE_NAMESPACE: "nebulous-cd"

  # =====  Broker settings  =====
  EMS_SERVER_BROKER_PORT: "31617"
  BROKERCEP_ADDITIONAL_BROKER_CREDENTIALS: "aaa/111, bbb/222"                                           # ++++++++++++++++ ${P_BROKERCEP_CREDENTIALS:-}
  # BROKERCEP_ADDITIONAL_BROKER_CREDENTIALS: "ENC(axeJUxNHajYfBffUwvuT3kwTgLTpRliDMz/ZQ9hROZ3BNOv0Idw72NJsawzIZRuZ)"
  BROKERCEP_EVENT_RECORDER_ENABLED: "false"
  BROKERCEP_EVENT_RECORDER_FILTER_MODE: "ALL"

  # =====  Baguette Server settings  =====
  BAGUETTE_SERVER_CREDENTIALS: '{ "aa":"xx" }'                                              # ++++++++++++++++ ${P_BAGUETTE_SERVER_CREDENTIALS:-{}}
  # BAGUETTE_SERVER_CREDENTIALS: "ENC(y46CiW6przlpXvz8ToE+T1Sn6uGfO2haP7OhATB0SXo=)"

  # =====  Baguette Client Install settings  =====
  EMS_SERVER_ADDRESS: "158.39.200.177"
  BAGUETTE_SERVER_ADDRESS: "158.39.200.177"
  BAGUETTE_SERVER_PORT: "32222"
  # BAGUETTE_CLIENT_INSTALL_INSTRUCTIONS_LINUX: "file:${EMS_CONFIG_DIR}/baguette-client-install/helm/app-detection.yml, file:${EMS_CONFIG_DIR}/baguette-client-install/helm/epm-deploy.yml, file:${EMS_CONFIG_DIR}/baguette-client-install/helm/netdata-deploy.yml"
  BAGUETTE_CLIENT_INSTALL_INSTALLATION_CONTEXT_PROCESSOR_PLUGINS: "eu.nebulous.ems.plugins.NebulousInstallationContextProcessorPlugin"

  #
  # =====  EMS server K8sClientInstaller configuration  =====
  #
  EMS_CLIENT_DEPLOYMENT_DRY_RUN: "false"
  K8S_SERVICE_ACCOUNT_SECRETS_PATH: "/var/run/secrets/kubernetes.io/serviceaccount"
  APP_CONFIG_MAP_NAME: "monitoring-configmap"
  EMS_CLIENT_CONFIG_MAP_NAME: "ems-client-configmap"
  # EMS_CLIENT_DAEMONSET_SPECIFICATION_FILE: "/ems-client-daemonset.yaml"
  EMS_CLIENT_DAEMONSET_NAME: "ems-client-daemonset"
  EMS_CLIENT_DAEMONSET_IMAGE_REPOSITORY: "registry.gitlab.com/nebulous-project/ems-main/ems-client"
  EMS_CLIENT_DAEMONSET_IMAGE_TAG: "latest"
  EMS_CLIENT_DAEMONSET_IMAGE_PULL_POLICY: "Always"

  # =====  EMS clients - Security and Authentication settings  =====
  EMS_CLIENT_ADDITIONAL_BROKER_CREDENTIALS: "aaa/111, bbb/222"
  # EMS_CLIENT_ADDITIONAL_BROKER_CREDENTIALS: "ENC(axeJUxNHajYfBffUwvuT3kwTgLTpRliDMz/ZQ9hROZ3BNOv0Idw72NJsawzIZRuZ)"
  # EMS_CLIENT_BROKER_USERNAME: "ccc"    # It is appended to EMS_CLIENT_ADDITIONAL_BROKER_CREDENTIALS
  # EMS_CLIENT_BROKER_PASSWORD: "333"
  EMS_CLIENT_KEYSTORE_SECRET: ""
  EMS_CLIENT_TRUSTSTORE_SECRET: ""
