apiVersion: apps/v1
kind: Deployment
metadata:
  name: sal-all-flux
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: sal-flux
  template:
    metadata:
      labels:
        app: sal-flux
    spec:
      containers:
        - name: mariadb
          image: {{ .Values.image.mariadb }}
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sal-mariadb-root-credentials-flux
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              value: {{ .Values.mariadb.database }}
        - name: sal
          image: {{ .Values.image.sal }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            - containerPort: 9001
          env:
            - name: MYSQL_DATABASE
              value: {{ .Values.mariadb.database }}
            - name: PROPERTIES_FILENAME
              value: {{ .Values.sal.propertiesFilename }}
            - name: PWS_URL
              value: {{ .Values.sal.pwsUrl }}
            - name: PWS_USERNAME
              value: {{ .Values.sal.pwsUsername }}
            - name: PWS_PASSWORD
              value: {{ .Values.sal.pwsPassword }}
            - name: DB_USERNAME
              value: "root"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sal-mariadb-root-credentials-flux
                  key: mysql-root-password
            - name: DB_DRIVER_CLASSNAME
              value: {{ .Values.sal.dbDriverClassname }}
            - name: DB_URL
              value: "jdbc:mariadb://localhost:3306/{{ .Values.mariadb.database }}"
            - name: DB_PLATFORM
              value: {{ .Values.sal.dbPlatform }}
            - name: JPDA_ADDRESS
              value: {{ .Values.sal.jpdaAddress }}
            - name: JPDA_TRANSPORT
              value: {{ .Values.sal.jpdaTransport }}
