{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "elasticsearch-chart.fullname" . }}
  namespace: {{ .Values.elasticsearch.namespace }}
  labels:
    app: {{ include "elasticsearch-chart.name" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "elasticsearch-chart.fullname" . }}
  labels:
    k8s-app: {{ include "elasticsearch-chart.name" . }}
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
rules:
  - apiGroups:
      - ""
    resources:
      - "services"
      - "namespaces"
      - "endpoints"
    verbs:
      - "get"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "elasticsearch-chart.fullname" . }}
  namespace: {{ .Values.elasticsearch.namespace }}
  labels:
    k8s-app: {{ include "elasticsearch-chart.name" . }}
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
subjects:
  - kind: ServiceAccount
    name: {{ include "elasticsearch-chart.fullname" . }}
    namespace: {{ .Values.elasticsearch.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "elasticsearch-chart.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
