apiVersion: v1
kind: Service
metadata:
  name: {{ include "elasticsearch-chart.fullname" . }}
  namespace: {{ .Values.elasticsearch.namespace }}
  labels:
    app: {{ include "elasticsearch-chart.name" . }}
spec:
  selector:
    app: {{ include "elasticsearch-chart.name" . }}
  ports:
    - name: rest
      port: {{ .Values.elasticsearch.service.ports.rest | default 9200 }}
      targetPort: rest
    - name: inter-node
      port: {{ .Values.elasticsearch.service.ports.interNode | default 9300 }}
      targetPort: inter-node
  type: {{ .Values.elasticsearch.service.type | default "ClusterIP" }}
