replicaCount: 1

image:
  repository: activeeon/sal
  pullPolicy: IfNotPresent
  tag: "dev"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8080
  pdaPort: 9001

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

mariadb:
  rootPassword: YWN0aXZlZW9u
  image:
    repository: mariadb
    pullPolicy: IfNotPresent
    tag: "latest"
  securityContext: {}
  resources: {}

scripts:
  sourceDir: installation-scripts-onm
  image:
    repository: quay.io/nebulous/sal-scripts
    pullPolicy: IfNotPresent
    tag: "main"

# SAL config
pws:
  url: ""
  username: ""
  password: ""

pv:
  name: mariadb-pv
  storage: 10Gi
  accessMode: ReadWriteOnce
  hostPath: /data/mariadb

pvc:
  name: mariadb-pvc
  storage: 10Gi
  accessMode: ReadWriteOnce
  claimName: "mariadb-pvc"
