replicaCount: 1

image:
  mariadb: mariadb
  sal: alijawad/sal:sql-fix
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80
  sal:
    port: 8080
  pda:
    port: 9001

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http

readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

mariadb:
  host: "sal-mariadb-root-credentials-flux"
  rootPassword: YWN0aXZlZW9u
  database: proactive

sal:
  propertiesFilename: sal
  pwsUrl: http://158.39.77.68:8880/
  pwsUsername: admin
  pwsPassword: admin
  dbUsername: root
  dbDriverClassname: org.mariadb.jdbc.Driver
  dbUrl: jdbc:mariadb://127.0.0.1:3306/proactive
  dbPlatform: org.hibernate.dialect.MariaDB53Dialect
  jpdaAddress: "9001"
  jpdaTransport: dt_socket
