apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nebulous-sal.fullname" . }}-mariadb-credentials
  labels:
    {{- include "nebulous-sal.labels" . | nindent 4 }}
type: Opaque
data:
  mysql-root-password: {{ .Values.mariadb.rootPassword | b64enc | quote }}
