apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nebulous-sal.fullname" . }}-pws-credentials
  labels:
    {{- include "nebulous-sal.labels" . | nindent 4 }}
type: Opaque
data:
  pws-user-password: {{ .Values.pws.password | b64enc | quote }}
