apiVersion: v1
kind: Service
metadata:
  name: {{ include "nebulous-sal.fullname" . }}-pda
  labels:
    {{- include "nebulous-sal.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.pdaPort }}
      targetPort: pda
      protocol: TCP
      name: pda
  selector:
    {{- include "nebulous-sal.selectorLabels" . | nindent 4 }}
