{{- if eq .Values.ingress.enabled true }}
{{- if or (eq .Values.ingress.clusterIssuer.selfSigned.enabled true) (eq .Values.ingress.clusterIssuer.letsEncrypt.enabled true) }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-issuer
spec:
  {{- if eq .Values.ingress.clusterIssuer.selfSigned.enabled true }}
  selfSigned: {}
  {{ end }}
  {{- if eq .Values.ingress.clusterIssuer.letsEncrypt.enabled true }}
  acme:
    # The ACME server URL
    server:  {{ .Values.ingress.clusterIssuer.letsEncrypt.server | quote }}
    # Email address used for ACME registration
    email: {{ .Values.ingress.clusterIssuer.letsEncrypt.email | quote }}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-secret
    # Enable the HTTP-01 challenge provider
    solvers:
      - http01:
          ingress:
            class: {{ .Values.ingress.ingressClassName }}
  {{ end }}
{{ end }}
{{ end }}