{{- if eq .Values.ingress.enabled true }}
{{- if eq .Values.ingress.providedCertificate.enabled true }}
apiVersion: v1
kind: Secret
metadata:
  name: provided-tls-secret
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.ingress.providedCertificate.tls.crt | quote }}
  tls.key: {{ .Values.ingress.providedCertificate.tls.key | quote }}
{{ end }}
{{ end }}