{{- if and .Values.server.enabled .Values.server.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "argo-workflows.serverServiceAccountName" . }}
  namespace: {{ include "argo-workflows.namespace" . | quote }}
  labels:
    {{- include "argo-workflows.labels" (dict "context" . "component" .Values.server.name "name" .Values.server.name) | nindent 4 }}
  {{- with .Values.server.serviceAccount.labels  }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.server.serviceAccount.annotations  }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ template "argo-workflows.serverServiceAccountName" . }}
    namespace: {{ include "argo-workflows.namespace" . | quote }}
roleRef:
  kind: Role
  name: {{ template "argo-workflows.server.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
