---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: proactive-deployment-scheduler
  labels:
    app: proactive-scheduler
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.scheduler.storage | default "10Gi" }}

