apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: workflowworkers.workflow.io
spec:
  group: workflow.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                cpu:
                  type: string
                ephemeral-storage:
                  type: string
                memory:
                  type: string
                pods:
                  type: string
                hugepages-1Gi:
                  type: string
                hugepages-2Mi:
                  type: string
                replicas:
                  type: integer
  scope: Cluster
  names:
    plural: workflowworkers
    singular: workflowworker
    kind: WorkflowWorkers
    shortNames:
    - wfw
    - wfws