{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nebulous-workflow-executor.serviceAccountName" . }}
  labels:
    {{- include "nebulous-workflow-executor.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: {{.Release.namespace}}
  name: workflow-executor 
rules:
- apiGroups: ["core"]
  resources: ["nodes"]
  verbs: ["get", "list", "watch", "patch"]
- apiGroups: ["argoproj.io"]
  resources: ["workflows"]
  verbs: ["get", "list", "watch", "patch"]
- apiGroups: ["workflow.io"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: workflow-executor 
  namespace: argo
subjects:
- kind: ServiceAccount
  name: {{ include "nebulous-workflow-executor.serviceAccountName" . }}
  namespace: {{.Release.namespace}}
roleRef:
  kind: ClusterRole
  name: workflow-executor
  apiGroup: rbac.authorization.k8s.io
{{- end }}