{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nebulous-workflow-executor.serviceAccountName" . }}
  labels:
    {{- include "nebulous-workflow-executor.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ include "Release.namespace" . }}
  name: workflow-executor 
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["GET", "LIST", "WATCH", "PATCH"]
- apiGroups: ["argoproj.io"]
  resources: ["workflows"]
  verbs: ["GET", "LIST", "WATCH", "UPDATE", "PATCH"]
- apiGroups: ["workflow.io"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflow-executor 
  namespace: argo
subjects:
- kind: ServiceAccount
  name: {{ include "nebulous-workflow-executor.serviceAccountName" . }}
  namespace: {{ include "Release.namespace" .  }}
roleRef:
  kind: Role
  name: workflow-executor
  apiGroup: rbac.authorization.k8s.io
{{- end }}