apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-storage
spec:
  {{- if .Values.influxdb.storageClassName }}
  storageClassName: {{ .Values.influxdb.storageClassName | quote }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.influxdb.storage | quote }}
